In [1]:
import numpy as np

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [2]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
impar = array1[::2]
impar

array([1, 3, 5, 7, 9])

In [5]:
filtro = array1%2!=0
impar2 = array1[filtro]
impar2

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [3]:
zera_impar = np.where(array1%2==0, array1, 0)
zera_impar

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
temp = np.genfromtxt(url, delimiter=',')
iris = temp[:10,:4]
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [16]:
np.mean(iris[:,0], axis=0)

4.859999999999999

In [17]:
np.median(iris[:,0], axis=0)

4.9

In [18]:
np.std(iris[:,0], axis=0)

0.2764054992217051

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [23]:
filtro = (iris[:,2]>1.5) & (iris[:,0]<5.0)
iris[filtro]

array([], shape=(0, 4), dtype=float64)

In [24]:
filtro2 = (iris[:,2]>=1.5) & (iris[:,0]<5.0)
iris[filtro2]

array([[4.6, 3.1, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

6 - Esse dataset possui nans?

In [26]:
np.isnan(iris).sum()

0

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [29]:
volume = ( np.pi * iris[:,2] * iris[:,0]**2 ) / 3

In [42]:
iris2 = np.insert(iris, 4, volume, axis = 1)
iris2

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       , 38.13265163],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       , 35.20049849],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       , 30.07237208],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       , 33.23805027],
       [ 5.        ,  3.6       ,  1.4       ,  0.2       , 36.65191429],
       [ 5.4       ,  3.9       ,  1.7       ,  0.4       , 51.91167701],
       [ 4.6       ,  3.4       ,  1.4       ,  0.3       , 31.02218026],
       [ 5.        ,  3.4       ,  1.5       ,  0.2       , 39.26990817],
       [ 4.4       ,  2.9       ,  1.4       ,  0.2       , 28.38324243],
       [ 4.9       ,  3.1       ,  1.5       ,  0.1       , 37.71481981]])